---
title: "Overview XYZT variables"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```


```{r set_paths, include=FALSE}

path_cmorized_annual <-
  "/net/kryo/work/loher/ROMS/RECCAP2/SO_d025_global_proto/submit_20211008/"

```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
library(ncdf4)
library(units)
```

# File names

```{r define}

overview <-
  read_csv("data/overview/overview_files.csv")

variables <-
  overview %>%
  filter(experiment_id == "ancillary") %>%
  distinct(variable_id) %>%
  pull()


```

# Plots

Below, please find plots of the variables:

- `r variables`


## T shape variables

```{r T_variables}

i_variable <- "Atm_CO2"
i_variable

# read list of all files
file <- paste(i_variable,
              "_ROMS-SouthernOcean-ETHZ_1_gr_1980-2018_v20211008.nc",
              sep = "")
print(file)

# read in data
variable_data <-
  tidync(paste(path_cmorized_annual,
               file,
               sep = ""))

# convert to tibble
variable_data_tibble <- variable_data %>%
  hyper_tibble()

# remove open link to nc file
rm(variable_data)

variable_data_tibble %>%
  ggplot(aes(time_mon, Atm_CO2)) +
  geom_path() +
  geom_point()

```


## XYZ shape variables

```{r XYZ_variables}

variables <- c("volume", "mask_vol")

for (i_variable in variables) {
  # i_variable <- variables[1]
  
  # read list of all files
  file <- paste(i_variable,
                "_ROMS-SouthernOcean-ETHZ_1_gr_v20211008.nc",
                sep = "")
  print(file)
  
  # read in data
  variable_data <-
    tidync(paste(path_cmorized_annual,
                 file,
                 sep = ""))
  
  # convert to tibble
  variable_data_tibble <- variable_data %>%
    hyper_tibble()
  
  # remove open link to nc file
  rm(variable_data)
  
  print(
    variable_data_tibble %>%
      ggplot(aes(!!sym(i_variable), depth)) +
      geom_bin2d(bins = 100) +
      scale_y_reverse()  +
      scale_fill_viridis_c()
  )
  
  print(
    variable_data_tibble %>%
      ggplot(aes(!!sym(i_variable))) +
      geom_histogram()
  )
  
}

```

## XY shape variables

```{r XY_variables}

variables <- c("area", "mask_sfc")


for (i_variable in variables) {
  # i_variable <- variables[1]
  
  # read list of all files
  file <- paste(i_variable,
                "_ROMS-SouthernOcean-ETHZ_1_gr_v20211008.nc",
                sep = "")
  print(file)
  
  # read in data
  variable_data <-
    tidync(paste(path_cmorized_annual,
                 file,
                 sep = ""))
  
  # convert to tibble
  variable_data_tibble <- variable_data %>%
    hyper_tibble()
  
  # remove open link to nc file
  rm(variable_data)
  
  print(
    variable_data_tibble %>%
      ggplot(aes(lon, lat, fill=!!sym(i_variable))) +
      geom_raster() +
      scale_fill_viridis_c() +
      coord_quickmap(expand = 0)
  )

}

```

## Single values

```{r single_value_variables}

variables <- c("Area_tot_native", "Vol_tot_native")


for (i_variable in variables) {
  # i_variable <- variables[1]
  
  # read list of all files
  file <- paste(i_variable,
                "_ROMS-SouthernOcean-ETHZ_1_gr_v20211008.nc",
                sep = "")
  print(file)
  
  # read in data
  variable_data <-
    nc_open(file = paste(path_cmorized_annual,
                                file,
                                sep = ""),
                   suppress_dimvals = TRUE)
  
  print(ncvar_get(variable_data))
}


```

